name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t jayanianu/eventticketing-frontend ./Frontend
          docker build -t jayanianu/eventticketing-nginx ./nginx
          docker build -t jayanianu/eventticketing-api ./Backend

          docker push jayanianu/eventticketing-frontend
          docker push jayanianu/eventticketing-nginx
          docker push jayanianu/eventticketing-api
